---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: nginx-default
    image: leandelivery/docker-systemd:ubuntu-18.04
    command: /sbin/init
    privileged: true
    tmpfs:
      - /sys/fs/cgroup
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: ubuntu1804
verifier:
  name: testinfra
  lint:
    name: flake8
